# Generated by Django 2.1 on 2018-08-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_mlcommenting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='object_pk',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
