# Generated by Django 2.1 on 2018-08-08 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('django_mlcommenting', '0002_comment_object_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='object_pk',
        ),
    ]
