# Generated by Django 2.1 on 2018-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_mlcommenting', '0004_comment_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(
                choices=[(5, 'very good'), (4, 'good'), (3, 'ok'), (2, 'poor'), (1, 'pretty poor')],
                verbose_name='comment rating'),
        ),
    ]
